// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package db

import (
	"context"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (note) VALUES (?) RETURNING id, note, created_at
`

func (q *Queries) CreateNote(ctx context.Context, note string) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, note)
	var i Note
	err := row.Scan(&i.ID, &i.Note, &i.CreatedAt)
	return i, err
}

const deleteAllNotes = `-- name: DeleteAllNotes :many
DELETE FROM notes RETURNING id, note, created_at
`

func (q *Queries) DeleteAllNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, deleteAllNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(&i.ID, &i.Note, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteNoteByID = `-- name: DeleteNoteByID :one
DELETE FROM notes WHERE id = ? RETURNING id, note, created_at
`

func (q *Queries) DeleteNoteByID(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, deleteNoteByID, id)
	var i Note
	err := row.Scan(&i.ID, &i.Note, &i.CreatedAt)
	return i, err
}

const getNote = `-- name: GetNote :one
SELECT id, note, created_at FROM notes WHERE id = ?
`

func (q *Queries) GetNote(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(&i.ID, &i.Note, &i.CreatedAt)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, note, created_at FROM notes
`

func (q *Queries) ListNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(&i.ID, &i.Note, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
