// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, note string) (Note, error)
	DeleteAllNotes(ctx context.Context) ([]Note, error)
	DeleteNoteByID(ctx context.Context, id int64) (Note, error)
	GetNote(ctx context.Context, id int64) (Note, error)
	ListNotes(ctx context.Context) ([]Note, error)
}

var _ Querier = (*Queries)(nil)
